# Generated by Django 5.0.2 on 2025-02-24 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_backdrop_path_alter_movie_poster_path'),
    ]

    operations = [
    ]
