# Generated by Django 5.0.2 on 2025-02-25 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20250224_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(related_name='movie_actors', through='movies.MovieCast', to='movies.person'),
        ),
        migrations.AlterField(
            model_name='moviecast',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_cast', to='movies.movie'),
        ),
    ]
