# Generated by Django 5.0.2 on 2025-02-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_auto_20250222_1816"),
        ("movies", "0005_alter_movie_cast_alter_movie_crew_and_more"),
    ]

    operations = []
