# Generated by Django 5.0.2 on 2025-02-26 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_merge_20250225_1638"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moviecast",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="moviecast",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="moviecast",
            name="character",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="moviecast",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
            ),
        ),
        migrations.AlterField(
            model_name="moviecast",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="moviecast",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movies.person"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="moviecast",
            unique_together={("movie", "person", "character")},
        ),
    ]
